language: go

os:
  - linux
  - osx
  - windows

go:
  - 1.11.x

before_script:
  - export GO111MODULE=on
  - make ensure

script:
  - make style_check
  - make test PKG=./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
